{
 "title": "SolarEdge2MQTT Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "agg", "label": "Aggregate Window Every", "query": "1h,1d,1w,1mo,1y" },
   { "name": "sebucket", "label": "SolarEdge Bucket", "query": "solaredge,solaredgedev" }
  ]
 },
 "panels": [
  { "title": "PV Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production AC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nitems = [\n  \"grid_delivery\",\n  \"consumer_used_battery_production\",\n  \"consumer_used_pv_production\",\n]\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => contains(value: r._field, set: items))\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      \"Grid delivery\": r.grid_delivery,\n      \"Battery used\": r.consumer_used_battery_production,\n      \"Direct used\": r.consumer_used_pv_production\n  }))\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> keep(columns: [\"_time\", \"Grid delivery\", \"Battery used\", \"Direct used\"])"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nitems = [\n  \"grid_delivery\",\n  \"grid_consumption\",\n  \"consumer_used_battery_production\",\n  \"consumer_used_pv_production\",\n  \"inverter_consumption\"\n]\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => contains(value: r._field, set: items))\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      \"Inverter\": r.inverter_consumption,\n      \"Direct\": r.consumer_used_pv_production,\n      \"Battery\": r.consumer_used_battery_production,\n      \"Grid\": r.grid_consumption - r.inverter_consumption,\n  }))\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> keep(columns: [\"_time\", \"Grid\", \"Direct\", \"Battery\", \"Inverter\"])"
    }
   ]
  },
  {
   "title": "Consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"math\"\n\nitems = [\n  \"grid_delivery\",\n  \"consumer_used_battery_production\",\n  \"inverter_production\",\n  ]\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => contains(value: r._field, set: items))\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      \"Grid delivery\":\n        math.round(x: r.grid_delivery / r.inverter_production * 100.0),\n      \"Battery used\":\n        math.round(x: r.consumer_used_battery_production / r.inverter_production * 100.0)\n  }))\n  |> map(fn: (r) => ({r with \"Direct used\": \n    if 100.0 - r[\"Grid delivery\"] - r[\"Battery used\"] < 0 then\n      0.0\n    else\n      100.0 - r[\"Grid delivery\"] - r[\"Battery used\"]}))\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> keep(columns: [\"_time\", \"Battery used\", \"Grid delivery\", \"Direct used\"])"
    }
   ]
  },
  {
   "title": "Sufficiency rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"math\"\n\nitems = [\n  \"grid_consumption\",\n  \"consumer_used_pv_production\",\n  \"consumer_used_battery_production\",\n  \"consumer_total\",\n]\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => contains(value: r._field, set: items))\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      \"Grid\": \n        if r.consumer_total > 0.0  then\n          math.round(x: (r.grid_consumption / r.consumer_total * 100.0))\n        else\n          0.0,\n      \"Battery\":\n          math.round(x: (r.consumer_used_battery_production / r.consumer_total * 100.0))\n  }))\n  |> map(fn: (r) => ({r with \"Direct\": \n    if 100.0 - r.Grid - r.Battery < 0 then\n      0.0\n    else\n      100.0 - r.Grid - r.Battery}))\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> keep(columns: [\"_time\", \"Grid\", \"Direct\", \"Battery\"])"
    }
   ]
  },
  {
   "title": "Production DC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pv_production\")\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg}), _value: if exists r._value then r._value else 0.0}))\n  |> set(key: \"_field\", value: \"Production\")\n  |> keep(columns: [\"_time\", \"_field\" \"_value\"])"
    },
    {
     "query": "import \"date\"\nimport \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: true)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))"
    }
   ]
  },
  {
   "title": "Power DC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pv_production\")\n  |> filter(fn: (r) => r.agg_type == \"mean\")\n  |> aggregateWindow(every: ${agg}, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> set(key: \"_field\", value: \"Power\")\n  |> keep(columns: [\"_time\", \"_field\" \"_value\"])"
    },
    {
     "query": "import \"date\"\nimport \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: ${agg}, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg}), _value: if exists r._value then r._value else 0.0}))"
    }
   ]
  },
  {
   "title": "Grid meter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"grid_consumption\" or r[\"_field\"] == \"grid_delivery\" )\n  |> aggregateWindow(every: ${agg}, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> map(fn: (r)=>({r with _field: if r._field == \"grid_consumption\" then \"Consumption\" else \"Delivery\"}))\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state_of_charge\")\n  |> filter(fn: (r) => r.agg_type == \"mean\")\n  |> filter(fn: (r) => r._value >= 0)\n  |> aggregateWindow(every: ${agg}, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _time: date.truncate(t: date.sub(d: 1s, from: r._time), unit: ${agg})}))\n  |> set(key: \"_field\", value: \"SoC\")\n  |> keep(columns: [\"_time\", \"_field\" \"_value\"])"
    }
   ]
  },
  {
   "title": "Grid meter - Average per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"grid_consumption\" or r[\"_field\"] == \"grid_delivery\")\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({r with hour: date.hour(t: r._time)}))\n  |> group(columns: [\"_field\", \"hour\"], mode: \"by\")\n  |> mean()\n  |> map(fn: (r) => ({r with _name: if r.hour < 10 then \"0\" + string(v: r.hour) else string(v: r.hour)}))\n  |> map(fn: (r) => ({r with _field: if r._field == \"grid_consumption\" then \"Consumption\" else \"Delivery\" }))\n  |> group()\n  |> pivot(rowKey: [\"_name\"], columnKey:[\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Grid meter - Average per weekday",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nweekdays = [\"Montag\", \"Dienstag\", \"Mittwoch\", \"Donnerstag\", \"Freitag\", \"Samstag\", \"Sonntag\"]\n\nfrom(bucket: \"${sebucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"grid_consumption\" or r[\"_field\"] == \"grid_delivery\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1s, from: r._time)}))\n  |> map(fn: (r) => ({r with weekday: date.weekDay(t: r._time)}))\n  |> map(fn: (r) => ({r with weekday: if r.weekday == 0 then 7 else r.weekday}))\n  |> group(columns: [\"_field\", \"weekday\"])\n  |> mean()\n  |> sort(columns: [\"weekday\"])\n  |> map(fn: (r) => ({r with _name: weekdays[r.weekday - 1]}))\n  |> map(fn: (r) => ({r with _field: if r._field == \"grid_consumption\" then \"Consumption\" else \"Delivery\" }))\n  |> group()\n  |> pivot(rowKey: [\"_name\"], columnKey:[\"_field\"], valueColumn: \"_value\")"
    }
   ]
  }
 ]
}